---
meta:
  name:    cron
  release: Cron BOSH Release
  target:  pipes
  url:     https://pipes.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  git:
    name: Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  bosh-lite:
    target:   https://10.128.4.73:25555
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   cron-boshrelease
    branch: master
    private_key:  ((github.private-key))
    access_token: ((github.access-token))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
